services:
  - type: web
    name: abhiwebsolutions
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: abhiweb-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: abhiweb_db
      - key: DB_USERNAME
        fromDatabase:
          name: abhiweb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: abhiweb-db
          property: password
databases:
  - name: abhiweb-db
    databaseName: abhiweb_db
    user: abhiwebuser
    plan: free
